# Project information
site_name: User Management Service
docs_dir: zoomin_docs
nav:
  - Home: index.md

site_author: Shubham Shivhare
site_description: >-
  Write your documentation in Markdown and create a professional static site in
  minutes – searchable, customizable, in 60+ languages, for all devices
# Repository
repo_name: SaaS-platform/asmp-user-management-service
repo_url: https://github.amdocsplatformx.com/SaaS-platform/asmp-user-management-service/

# Copyright
copyright: Copyright &copy; 2016 - 2024 Shubham Shivhare
