name: Documentation Deployment

on:
  push:
    branches:
      - master
      - '**' # All branches

jobs:
  docsBuildDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Service Repo
        uses: actions/checkout@v4

      - name: Install MkDocs with Material Theme
        run: |
          pip3 install mkdocs mkdocs-material

      - name: Build Documentation Site
        run: |
          mkdocs build

      # Deploy to GH Pages for the master branch
      - name: Deploy to GitHub Pages (Master)
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./site
          publish_branch: gh-pages-dev
          github_token: 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
          user_name: shubham7047
          user_email: shubham7047@gmail.com

      # Deploy to GH Pages for other branches
      - name: Deploy to GitHub Pages (Branch)
        if: github.ref != 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./site
          publish_branch: gh-pages-${{ github.ref_name }}
          github_token: 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
          user_name: shubham7047
          user_email: shubham7047@gmail.com
        # If the push is to any branch other than master, this step deploys the site to a branch named 'gh-pages-<branch-name>'
